#
- name: postgresql - ensure psycopg2 module is installed
  apt:
    name: "python-psycopg2"
    state: "present"

- include: install.yml
- include: setup.yml
  when: "not postgresql_tools_only|default(False)"

- include: bashd.yml
  when: "not postgresql_tools_only|default(False)"
